import assert from 'node:assert/strict';
import { test } from 'node:test';

import {
  CusumDrift,
  detectSteadyBlocks,
  errorQuantiles,
  fitHullCurveNNLS,
  hullPowerW,
  hullSpeedKmh,
  isotonicFit,
  vesselFromProfile,
} from '../js/vessel_model.js';

const PROFILE = {
  hull_efficiency_curve_kmh_whkm: [[4, 50], [6, 80], [8, 120]],
  hotel_load_w: 50,
  motor_max_power_w: 1164,
  pv_kwp: 1.0,
  pv_derating: 0.85,
  battery_capacity_kwh: 2.56,
};

test('fitHullCurveNNLS recovers a synthetic P = b1*v + b3*v^3 law', () => {
  const samples = [];
  for (let v = 2; v <= 8; v += 0.5) {
    samples.push({ stwKmh: v, powerW: 20 * v + 2 * v ** 3 });
  }
  const { b1, b3 } = fitHullCurveNNLS(samples);
  assert.ok(Math.abs(b1 - 20) < 0.5, `b1=${b1}`);
  assert.ok(Math.abs(b3 - 2) < 0.05, `b3=${b3}`);
});

test('fitHullCurveNNLS clamps coefficients at zero (never non-monotone)', () => {
  // Data generated by P = 2v^3 - 10v would want a negative linear term.
  const samples = [];
  for (let v = 3; v <= 8; v++) {
    samples.push({ stwKmh: v, powerW: 2 * v ** 3 - 10 * v });
  }
  const { b1, b3 } = fitHullCurveNNLS(samples);
  assert.equal(b1, 0);
  assert.ok(b3 > 1.5 && b3 < 2);
});

test('fitHullCurveNNLS handles degenerate inputs and weights', () => {
  assert.deepEqual(fitHullCurveNNLS([]), { b1: 0, b3: 0 });
  // All-zero speeds: both denominators are zero.
  assert.deepEqual(fitHullCurveNNLS([{ stwKmh: 0, powerW: 100 }]),
                   { b1: 0, b3: 0 });
  // A heavy weight drags the fit toward that sample.
  const light = fitHullCurveNNLS([
    { stwKmh: 5, powerW: 300 }, { stwKmh: 5, powerW: 600 },
  ]);
  const heavy = fitHullCurveNNLS([
    { stwKmh: 5, powerW: 300, weight: 100 }, { stwKmh: 5, powerW: 600 },
  ]);
  assert.ok(hullPowerW(heavy, 5) < hullPowerW(light, 5));
});

test('hullPowerW and hullSpeedKmh are consistent inverses', () => {
  const curve = { b1: 20, b3: 2 };
  assert.equal(hullPowerW(curve, 0), 0);
  assert.equal(hullPowerW(curve, -1), 0);
  assert.equal(hullPowerW(curve, 5), 20 * 5 + 2 * 125);
  assert.ok(Math.abs(hullSpeedKmh(curve, 350) - 5) < 0.01);
  assert.equal(hullSpeedKmh(curve, 0), 0);
  assert.equal(hullSpeedKmh(curve, -10), 0);
  assert.equal(hullSpeedKmh({ b1: 0, b3: 0 }, 500), 0);
});

test('isotonicFit passes monotone data through and pools violations', () => {
  assert.deepEqual(isotonicFit([1, 2, 3]), [1, 2, 3]);
  assert.deepEqual(isotonicFit([3, 1, 2]), [2, 2, 2]);
  const multi = isotonicFit([1, 3, 2, 5]);
  assert.deepEqual(multi, [1, 2.5, 2.5, 5]);
  for (let i = 1; i < multi.length; i++) {
    assert.ok(multi[i] >= multi[i - 1]);
  }
  assert.deepEqual(isotonicFit([]), []);
});

function steadyRows(t0, seconds, speedKmh, powerW) {
  const rows = [];
  for (let s = 0; s < seconds; s++) {
    rows.push({ t_s: t0 + s, speedKmh, powerW });
  }
  return rows;
}

test('detectSteadyBlocks gates on power CV, speed SD, floor values and settling',
     () => {
  const opts = { blockS: 30 };
  let t = 0;
  const rows = [];
  const add = (r) => { rows.push(...r); t += r.length; };
  add(steadyRows(t, 30, 5, 500));       // settling after start -> discarded
  add(steadyRows(t, 30, 5, 500));       // accepted
  const noisy = steadyRows(t, 30, 5, 500)
      .map((r, i) => ({ ...r, powerW: i % 2 ? 800 : 200 })); // CV too high
  add(noisy);
  add(steadyRows(t, 30, 5, 500));       // settling after noise -> discarded
  add(steadyRows(t, 30, 5.1, 505));     // accepted
  add(steadyRows(t, 30, 5, 0));         // meanP = 0: below minPowerW
  add(steadyRows(t, 30, 0.5, 500));     // too slow (meanV <= 1)
  const wobble = steadyRows(t, 30, 5, 500)
      .map((r, i) => ({ ...r, speedKmh: i % 2 ? 6 : 4 })); // speed SD too high
  add(wobble);
  add(steadyRows(t, 5, 5, 500));        // short tail -> break

  const blocks = detectSteadyBlocks(rows, opts);
  assert.equal(blocks.length, 2);
  assert.ok(Math.abs(blocks[0].stwKmh - 5) < 1e-9);
  assert.ok(Math.abs(blocks[0].powerW - 500) < 1e-9);
  assert.equal(blocks[0].n, 30);
  assert.ok(Math.abs(blocks[1].powerW - 505) < 1e-9);
});

test('detectSteadyBlocks defaults: 90 s blocks accepted after one settles',
     () => {
  const rows = [...steadyRows(0, 90, 5, 500), ...steadyRows(90, 90, 5, 500)];
  const blocks = detectSteadyBlocks(rows);
  assert.equal(blocks.length, 1);
});

test('CusumDrift trips on sustained bias in either direction', () => {
  const d = new CusumDrift();
  assert.equal(d.update(0.01), 0); // within allowance
  for (let i = 0; i < 4; i++) d.update(0.2);
  assert.equal(d.tripped, 1); // boat needs more power than modelled
  d.reset();
  assert.equal(d.tripped, 0);
  assert.equal(d.pos, 0);
  for (let i = 0; i < 4; i++) d.update(-0.2);
  assert.equal(d.tripped, -1);
});

test('errorQuantiles: conservative defaults, then calibration at 10 samples',
     () => {
  const empty = errorQuantiles([]);
  assert.deepEqual(empty, { p10: -0.25, p50: 0, p90: 0.25, calibrated: false });
  const few = errorQuantiles([0.1, -0.05, 0.02]);
  assert.equal(few.calibrated, false);
  const errs = [-0.1, -0.08, -0.05, -0.02, 0, 0.01, 0.03, 0.05, 0.08, 0.12];
  const q = errorQuantiles(errs);
  assert.equal(q.calibrated, true);
  assert.equal(q.p10, -0.08);
  assert.equal(q.p50, 0.01);
  assert.equal(q.p90, 0.12);
  assert.ok(q.p10 <= q.p50 && q.p50 <= q.p90);
});

test('vesselFromProfile seeds a monotone curve from the boat profile', () => {
  const v = vesselFromProfile(PROFILE);
  assert.ok(v.curve.b1 >= 0);
  assert.ok(v.curve.b3 > 0);
  assert.equal(v.hotelW, 50);
  assert.equal(v.motorMaxW, 1164);
  assert.equal(v.batteryKwh, 2.56);
  assert.deepEqual(v.relErrors, []);
  // The seeded curve should roughly reproduce the profile points.
  const p6 = hullPowerW(v.curve, 6);
  assert.ok(p6 > 300 && p6 < 650, `p6=${p6}`); // profile says 480 W
});
